language: node_js
node_js:
- stable
cache:
  direstories:
  - node_modules
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: v0EtexsWX1TZ/efulMvXzXvkiRk7wwztTKre8fpqoVnqpSbevmgC14l0HEFm3sCDri+/qx2d5sY7GSaqKtrC/nQbmswurfJq/Qkx2duSExZsbN8BftssmOan7RuexaviZVcP9vPUUG+8uLVJcd7bCf66y/K01oU83If9YcOh+zsrMm5qY5WAU96oZNxyPdW6sWdqk0OU7wzNqtBa7gDruXrXiHFvMqhMojB0hZmUSGHkK8jiLPIhuueK+3jAMghJ1gLiGEc5bCpX8fgbhGB4AWNP/ygdG5QzJSyLfnwBjb2xfyFYekWiW9zcLI/3/69S0w6FeOdM0qfrDE50cchptj1Lcp4hT5seeoTAWH1cUAMl3+HoCdwHPpmp0HNQw7qDULJyghAkc1pSfz/SDwWdJMQKw9+fSLJjcEqk+geELI9Uerc51Ecgo9/sl71EB5P/xRGjt+4VBYV5lymJzWRbxxYCYycg5inzTLFu/2Y4s5FuxqRB6GfhnwM2NGpEF8ttaXhWyeLvBOBJ9/JV3CsX8cMyeocpHSuW/TQWUD7Nt5JyME+X0gdCLKr1FIz5gCV/CgNhIfw7AdSNUuISp6em9YfKZKBTE7UBgM+0JuUdtC5WxxmKe46qHTi0rGiksw6vgqCCytW3zKHImjO7z+x2QzFz1Ecos/dH6soInoAytRg=
  app: desolate-dawn-10726
